name: Create and Publish Docker Image

on:
  workflow_call:
    inputs:
      aws-region:
        type: string
      image-name:
        type: string

permissions:
    id-token: write
    contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        env:
          TEST_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_AWS_GITHUB_ACTIONS_OICD_TERRAFORM_ROLE: ${{ secrets.AWS_GITHUB_ACTIONS_OICD_TERRAFORM_ROLE }}
        run: |
          echo ${#TEST_GITHUB_TOKEN}
          echo ${#TEST_AWS_GITHUB_ACTIONS_OICD_TERRAFORM_ROLE}

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_OICD_TERRAFORM_ROLE }}
          aws-region: ${{ inputs.aws-region }}
          role-session-name: GITHUB-OIDC-TERRAFORM

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: easecloud
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          